### ISSUE TITLE
[week5] 이왜틀......

### ISSUE THREAD

**Issue by sangminee** [kyukong/SeSAC-Algo#30]
public static void main(String[] args) throws IOException{
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringBuilder sb = new StringBuilder();
        while (true) {
            String str = br.readLine();
            if(str.equals("end")) break;

            char[] c = str.toCharArray();

            // 말 놓은 횟수
            int player1 = 0;
            int player2 = 0;

            char[][] arr = new char[3][3];
            int index = 0;
            for(int i=0; i<3; i++){
                for(int j=0; j<3; j++){
                    char temp = c[index];
                    index++;
                    arr[i][j] = temp;
                    if(temp == 'X') player1++;
                    else if(temp == 'O') player2++;
                }
            }

            // 빙고 찾기
            boolean check1 = false;
            boolean check2 = false;

            // 대각선 1
            if(arr[0][0] == 'X' && arr[1][1] == 'X' && arr[2][2] == 'X') check1 = true;
            if(arr[0][0] == 'O' && arr[1][1] == 'O' && arr[2][2] == 'O') check2 = true;

            // 대각선 2
            if(arr[0][2] == 'X' && arr[1][1] == 'X' && arr[2][0] == 'X') check1 = true;
            if(arr[0][2] == 'O' && arr[1][1] == 'O' && arr[2][0] == 'O') check2 = true;

            for(int i=0; i<3; i++){
                // 가로
                if(arr[i][0] == 'X' && arr[i][1] == 'X' && arr[i][2] == 'X') check1 = true;
                if(arr[i][0] == 'O' && arr[i][1] == 'O' && arr[i][2] == 'O') check2 = true;

                // 세로
                if(arr[0][i] == 'X' && arr[1][i] == 'X' && arr[2][i] == 'X') check1 = true;
                if(arr[0][i] == 'O' && arr[1][i] == 'O' && arr[2][i] == 'O') check2 = true;
            }

            if(player1 + player2 == 9 && check2){ // 게임판이 꽉 차있을 때, O가 이기는 경우
                sb.append("invalid\n");
            }else if(check1 && check2){ // player1 빙고인데 player2도 빙고일 경우
                sb.append("invalid\n");
            }else if(check1 && (player1 != player2+1)){  // player1 빙고일때,
                sb.append("invalid\n");
            }else if(check2 && (player1 != player2)){ // player2 빙고일때,
                sb.append("invalid\n");
            }else if(!check1 && !check2 && player1 != player2+1) { // 빙고가 존재하지 않을 때
                sb.append("invalid\n");
            }else{
                sb.append("valid\n");
            }
        }

        System.out.println(sb);
    }

**Comment by popopododo** [comment]
테스트 케이스와 함께 다시 올려주세요 🙏

**Comment by sangminee** [comment]
XXXOO.XXX
XOXOXOXOX
OXOXOXOXO
XXOOOXXOX
XO.OX...X
.XXX.XOOO
X.OO..X..
OOXXXOOXO
end

**Comment by sangeun99** [comment]
대각선인 경우가 두 가지 생기는 것도 고려해주세요

**Comment by sangeun99** [comment]
oox
xxo
oox일 경우 invalid한데 혹시 케이스가 invalid로 뜰까요?

**Comment by sangminee** [comment]
넵...
<img width="196" alt="스크린샷 2023-12-20 오후 12 15 41" src="https://github.com/kyukong/SeSAC-Algo/assets/81500474/f927aa7f-a74a-4d59-8c0e-377c37247267">

**Comment by popopododo** [comment]
문제 해결했으므로 닫겠습니다.
